### ISSUE TITLE
关于jquery-1.11.1.js 

### ISSUE THREAD

**Issue by xixiaofinland** [jiangxianli/wechatShare-JS#3]
请问是否一定有必要使用jquery? 这个文件有200+k 实在是太大了， 如非必要想能不能去掉？

**Comment by jiangxianli** [comment]
@Xixiao007 因为jquery.wechat.share.js使用jquery写的插件，所以jquery文件是一定要引入的，你可以压缩本地的jquery-1.11.1.js文件，或者使用jquery的cdn外链

**Comment by xixiaofinland** [comment]
谢谢@jiangxianli

还有一个问题： 我花了些时间看需要准备的东西。发现：

1）需要ICP备案的网站才能分享网站URL到朋友圈...
2）需要服务号. 订阅号没法获得appID appSecrete, 而且服务号又要求企业信息，个人是没法申请的。这么说，如果是个人开发的网站或者app，都没法使用微信的第三方帐号登录自己的网站或者app吗？

**Comment by jiangxianli** [comment]
@Xixiao007 是的，个人的公众号是没法做认证的，使用不了分享和微信登录功能。

**Comment by xixiaofinland** [comment]
谢谢！

**Comment by xixiaofinland** [comment]
谢谢！
